### ISSUE TITLE
Assertion error when running the uatg from-config command 

### ISSUE THREAD

**Issue by Pruthvi-Raj-S** [incoresemi/uatg#26]
**Chromite Bug Bounty**
1) we have installed all the tools and their dependency.
2) we cloned the uatg repo and ran the uatg setup command.
3) we made the path corrections in config.ini file and also enabled few test cases in index.yaml
4) we tried to run the command "uatg from-config -c config.ini -v debug", but there is an assertion error. here is the error we got
![image](https://user-images.githubusercontent.com/87191910/169313160-2ee1c5e4-feed-4ca0-b4e5-9e04793cf702.png)

Note:-  This error is only occurring only when we try generating a cache test case, **Its able to generate test case for other module, like branch_predictor**

We are using
uatg version - 1.3.0
python version - 3.8.10

**This is the index.yaml file**
![image](https://user-images.githubusercontent.com/87191910/169317895-9bba430c-3805-441d-9a18-42e8c7ab27e6.png)
![image](https://user-images.githubusercontent.com/87191910/169316504-5095eaeb-9e06-4976-90c7-39b09474e83e.png)

**This is the config.ini file**
![image](https://user-images.githubusercontent.com/87191910/169318150-0e7396b3-f45d-4ad4-9b87-8d924ba2ba05.png)
![image](https://user-images.githubusercontent.com/87191910/169318239-5bf15cd6-75da-4ed5-96b4-7e08172f4913.png)

**This is the core_config.yaml**
![image](https://user-images.githubusercontent.com/87191910/169318507-358902a4-0995-4322-b267-019d532f2641.png)

**Comment by Alenkruth** [comment]
Hi @Pruthvi-Raj-S 

The version of UATG you are using is old. Please try the same with UATG 1.5.0 (current release), preferably in a new virtual environment.

Moreover, make sure you are using the ``dev`` branch of chromite_uatg_tests as well as the latest release of Chromite (using ``csr-box`` branch.

Let me know if it works.
Alenkruth

**Comment by Alenkruth** [comment]
For UATG Version 1.5.0 you will also have to update your config.ini file. I am attaching a link to my config.ini. Since the documentation is pretty outdated, the docs does not have the latest template. Sorry about that.

[config.ini](https://incoresemiconductorspvtltd-my.sharepoint.com/:u:/g/personal/alenkruth_km_incoresemi_com/EQZ5yzdqOyxHuzXY4HBZTD4Bb96j4GBbr_xlspRX49KF-A?e=HgAjmS)

--Alenkruth

**Comment by Alenkruth** [comment]
If you still face the issue even after trying all the above steps, Please send a complete log of UATG's execution.

`uatg from-config -c config.ini -v debug &> log.txt` should help you get the log file.

-- Alenkruth

**Comment by Pruthvi-Raj-S** [comment]
Hi @Alenkruth 

I did update the uatg and also replaced config.ini file, but for the path to the yaml files containing DUT Configuration. I had to rebuild the chromite core.

After cloning the chromite repo and changing the git status to using-csrbox.
I ran the python command present in the run.sh of the chromite repo

when i try to run "make generate_verilog" i do get this log  [glog.txt](https://github.com/incoresemi/uatg/files/8732791/glog.txt)

here is the log file when i do "make link_verilator"
[vlog.txt](https://github.com/incoresemi/uatg/files/8732792/vlog.txt)

**Comment by Alenkruth** [comment]
Hi,

While rebuilding chromite core, did you reinstall/update the requirements? That should be done using `pip install -r requirements.txt` in the chromite's root directory.

Moreover, you should also try to clean and rebuild chromite. Since, building using the command in ``run.sh`` without performing a ``--clean`` would result in using outdated dependencies. Append ``--clean`` to the command you used to rebuild to clean the cloned dependencies. Then rebuild again.

Let me know if it works.
Alenkruth

**Comment by Pruthvi-Raj-S** [comment]
Hi, 

Yes, I did do `pip3 install -r requirements.txt` before rebuilding the chromite core.

I did clean the cloned dependencies, by using `--clean` and rebuild the core again.

But I'm still getting an error, when I do `make generate_verilog`, this is the log file [newglog.txt](https://github.com/incoresemi/uatg/files/8737592/newglog.txt)

--Pruthvi

**Comment by Alenkruth** [comment]
I have tried rebuilding the core and i also tried the make command. But, I am unable to reproduce the error in my machine.

Can you check if the issue persists in any other machine of yours?

On a side note, you will have to use ``make link_verilator_elf`` once generate_verilog is done.

--Alenkruth

**Comment by Pruthvi-Raj-S** [comment]
Hi,

I tried cloning and building the core on a different path and did not encounter any errors while doing these commands 
`make generate_verilog`
`make link_verilator_elf`
`make generate_boot_files`

So i tried to run `make hello` on the benchmarks, and also created a link of `code.mem` in the bin directory.

But when i try to run the `./chromite_core +rtldump` , i get this error

![image](https://user-images.githubusercontent.com/87191910/169549245-e82697a4-9b07-403e-b809-38c9c081d0d4.png)

**Comment by HarithaRajaram** [comment]
Hello @Alenkruth Al,

To follow up with the same issue #26 

- I have build the chromite core, my `Make Hello` and `dhrystonemake dhrystone march=rv64im mabi=lp64 ITERATIONS=5000` works 
- I have installed the latest UATG version(1.5.0) , also have made the appropriate changes in config.ini file
- I was able to generate the ASM files 
- I have cloned the chromite-core-verif repo , compiled and tried running the ASM files during which i encountered an error which i have enclosed below in the compile report and run report
[Compile Test Report.pdf](https://github.com/incoresemi/uatg/files/8749413/Compile.Test.Report.pdf)
[Run Test Report.pdf](https://github.com/incoresemi/uatg/files/8749414/Test.Report.pdf)

**Comment by Alenkruth** [comment]
> Hi,
> 
> I tried cloning and building the core on a different path and did not encounter any errors while doing these commands `make generate_verilog` `make link_verilator_elf` `make generate_boot_files`
> 
> So i tried to run `make hello` on the benchmarks, and also created a link of `code.mem` in the bin directory.
> 
> But when i try to run the `./chromite_core +rtldump` , i get this error
> 
> ![image](https://user-images.githubusercontent.com/87191910/169549245-e82697a4-9b07-403e-b809-38c9c081d0d4.png)

you should add a ``+elf=<name_of_elf>`` along with the +rtldump flag.

Alenkruth

**Comment by Alenkruth** [comment]
hi,

you can use a +elf=<name_of_elf> in addition to the +rtldump parameter. it
should work.

-- Alenkruth
