### ISSUE TITLE
Bugs in the conda commands

### ISSUE THREAD

**Issue by snehashri04** [incoresemi/uatg#5]
While running the conda virtual environment https://uatg.readthedocs.io/en/latest/installation.html#using-conda-virtualenv-for-python, I came across small typos

"conda create --name <env-name> --python=3.7 --yes" should be " conda create --name <env-name> python=3.7 --yes"

"conda set --activate-base false" doesn't work. Alternatively, "conda config --set auto_activate_base false" worked

**Comment by Alenkruth** [comment]
Thank you for pointing out the errors. Sorry about that. 

I have already made the corrections and it will be merged to the main branch shortly. 

I will close this issue once the merge gets through.

**Comment by Alenkruth** [comment]
The issue has been fixed in [this](https://github.com/incoresemi/uatg/pull/4) merge. I am closing the issue.
